# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gcdiff < Formula
  desc "A terminal tool for comparing and auditing GCP resources across projects"
  homepage "https://github.com/tflynn3/gcdiff"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tflynn3/gcdiff/releases/download/v0.4.0/gcdiff_0.4.0_Darwin_x86_64.tar.gz"
      sha256 "765b53a49ecb0986f790cc51c23707044335d130097746b8b68031ce8f91d8a0"

      def install
        bin.install "gcdiff"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tflynn3/gcdiff/releases/download/v0.4.0/gcdiff_0.4.0_Darwin_arm64.tar.gz"
      sha256 "b9f609d9c5705e2806e0e592782b7cd43bf27102a0c1a0df3b95d4af365c6b7a"

      def install
        bin.install "gcdiff"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tflynn3/gcdiff/releases/download/v0.4.0/gcdiff_0.4.0_Linux_x86_64.tar.gz"
      sha256 "ca9d59ee64169fc2deb31186f3c4844a9062734634ab22fdf37e626c0e2fb16e"
      def install
        bin.install "gcdiff"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tflynn3/gcdiff/releases/download/v0.4.0/gcdiff_0.4.0_Linux_arm64.tar.gz"
      sha256 "463a18392ff5604d66643ee398d8f747b1f1c9e3dd59fe60527969a5cc437ee9"
      def install
        bin.install "gcdiff"
      end
    end
  end

  test do
    system "#{bin}/gcdiff", "--version"
  end
end
