# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gcdiff < Formula
  desc "A terminal tool for comparing and auditing GCP resources across projects"
  homepage "https://github.com/tflynn3/gcdiff"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tflynn3/gcdiff/releases/download/v0.1.0/gcdiff_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "66e835508ae580126fed01ec2305b1eaedca111beaecc7af04d141bb0be6ba76"

      def install
        bin.install "gcdiff"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tflynn3/gcdiff/releases/download/v0.1.0/gcdiff_0.1.0_Darwin_arm64.tar.gz"
      sha256 "51203721bfe27bd803f8603fb178f5d3fba18d22bd5078b6ff797beb924492f7"

      def install
        bin.install "gcdiff"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tflynn3/gcdiff/releases/download/v0.1.0/gcdiff_0.1.0_Linux_x86_64.tar.gz"
      sha256 "0e66564a6d997518f612c0484652d5debf151399a64941b14c4f809285246b01"
      def install
        bin.install "gcdiff"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tflynn3/gcdiff/releases/download/v0.1.0/gcdiff_0.1.0_Linux_arm64.tar.gz"
      sha256 "e1bd0cde183da468334c31ed9acf191edd4859ba35b8020b70f407a9344a5b7a"
      def install
        bin.install "gcdiff"
      end
    end
  end

  test do
    system "#{bin}/gcdiff", "--version"
  end
end
