# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gcdiff < Formula
  desc "A terminal tool for comparing and auditing GCP resources across projects"
  homepage "https://github.com/tflynn3/gcdiff"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tflynn3/gcdiff/releases/download/v0.3.1/gcdiff_0.3.1_Darwin_x86_64.tar.gz"
      sha256 "c1cf88d1ffae583d810d5b5f9a60092f8c47d4442d0f68c780f68375edeb177a"

      def install
        bin.install "gcdiff"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tflynn3/gcdiff/releases/download/v0.3.1/gcdiff_0.3.1_Darwin_arm64.tar.gz"
      sha256 "05c501a2236ece77d767faf132da03c1c587cf8ec63d0d6955c9469eb98b37cb"

      def install
        bin.install "gcdiff"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tflynn3/gcdiff/releases/download/v0.3.1/gcdiff_0.3.1_Linux_x86_64.tar.gz"
      sha256 "89d29c6d46b636a30966944c1a857c52a5c4423836035f8868deb3ff9c57adac"
      def install
        bin.install "gcdiff"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tflynn3/gcdiff/releases/download/v0.3.1/gcdiff_0.3.1_Linux_arm64.tar.gz"
      sha256 "3145b0b7f3880e6bc5ddcd4249a70d302069e9caa54ef2eda3e1ccc9e3e17ce4"
      def install
        bin.install "gcdiff"
      end
    end
  end

  test do
    system "#{bin}/gcdiff", "--version"
  end
end
